// import { Inter } from 'next/font/google';
import { Providers } from '@/lib/components/ui/Providers';

export const metadata = {
  title: 'Welcome to personal-blog',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
